### ISSUE TITLE
Missing `is-semver` in `package.json`

### ISSUE THREAD

**Issue by thomas-riccardi** [IonicaBizau/gpm#14]
A recent commit b757418b80f0e4680fedd08799fe5720da368655 added a dependence on `is-semver`, but forgot to add it to the `package.json` file. 

```
$ gpm -h
module.js:328
    throw err;
    ^

Error: Cannot find module 'is-semver'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (gpm/lib/index.js:17:18)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)

```

**Comment by IonicaBizau** [comment]
Whoups! Thanks for head's up! :+1:
